MEMORY
{
  CORE0_LM_SLV : ORIGIN = 0x01000000, LENGTH = 512K
  AXI_SRAM : ORIGIN = 0x01080000, LENGTH = 1M
}

REGION_ALIAS("REGION_TEXT", CORE0_LM_SLV);
REGION_ALIAS("REGION_RODATA", CORE0_LM_SLV);
REGION_ALIAS("REGION_DATA", AXI_SRAM);
REGION_ALIAS("REGION_BSS", AXI_SRAM);
REGION_ALIAS("REGION_HEAP", AXI_SRAM);
REGION_ALIAS("REGION_STACK", AXI_SRAM);
